enabled: true
titleOnly: true
commitsOnly: false
titleAndCommits: false
types:
  - build
  - chore
  - ci
  - docs
  - feat
  - fix
  - style
  - refactor
  - perf
  - test
  - revert
targetUrl: https://www.conventionalcommits.org/en/v1.0.0/
