builds:
- head-branch: ['^build']

bugs:
- head-branch: ['^fix/', '^hotfix/']

deploy:
- head-branch: ['^deploy']

ci:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', 'renovate.json5']
- head-branch: ['^ci/']

deps:
- head-branch: ['^renovate/', '^deps/']
- changed-files:
  - any-glob-to-any-file:
    - 'node/.node-version'
    - 'python/.python-version'
    - 'go/go.work'
    - 'go/**/*/go.mod'

docs:
- changed-files:
  - any-glob-to-any-file: ['**/README.md', '**/CHANGELOG.md']

features:
- head-branch: ['^feat']

lang/python:
- changed-files:
  - any-glob-to-any-file: ['python/**/*']

lang/go:
- changed-files:
  - any-glob-to-any-file: ['go/**/*']

lang/node:
- changed-files:
  - any-glob-to-any-file: ['node/**/*']

renovate:
- head-branch: ['^renovate/']

tests:
- changed-files:
  - any-glob-to-any-file:
    - '**/*/test_*'
    - '**/*/*_test'
