# Configuration file for Circle CI testings
version: 2.1
executors:
  bash_python_executor:
    docker:
      - image: python:3.4.3
    shell: bash

jobs:
  run_test_code:
    executor: bash_python_executor
    working_directory: ~/codewars
    steps:
      - checkout
      - run:
          name: Checkout to latest directory and run test code
          command: |
            cd $(dirname $(git diff --name-only HEAD HEAD^1 |head -n 1))
            pwd
            python3 test_*.py
 
workflows:
  version: 2.1
  workflows:
    jobs:
      - run_test_code