# Configuration file for Circle CI testings
version: 2.1
executors:
  unittest_executor:
    docker:
      - image: wakabh56/codewars-sandbox:latest
    shell: bash

jobs:
  run_test_code:
    executor: unittest_executor
    working_directory: ~/codewars
    steps:
      - checkout
      - run:
          name: Checkout to latest directory and run test code
          command: |
            export EXTENSION=$(git diff --name-only HEAD HEAD^1 |head -n 1 |awk -F '[.]' '{print $2}')
            if [ $EXTENSION = "py" ] ; then cd $(dirname $(git diff --name-only HEAD HEAD^1 |head -n 1)) ; python3.4 test_*.py ; \
            elif [ $EXTENSION = "js" ]; then cd $(dirname $(git diff --name-only HEAD HEAD^1 |head -n 1)) ; node test_*.js ; \
            fi
 
workflows:
  version: 2.1
  workflows:
    jobs:
      - run_test_code